config/routes.rb
Rails.application.routes.draw do
  # resources :line_items
  resources :carts
  # get 'products/index'
  # get 'products/new'
  # get 'products/edit'
  # get 'products/show'
  resources :categories
  resources :products
  # get 'home/index'
  devise_for :users, controllers: {
    :registrations => "users/registrations",
    :sessions => "users/sessions"
  }
  devise_scope :user do 
    post "/sessions/disable/:id" => "users/sessions#disable" 
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root to: "home#index"
  # root to: "dashboard#index"
  authenticated :user do
    root 'home#index', as: :authenticated_root
  end

  unauthenticated :user do
    root 'dashboard#index', as: :unauthenticated_root
  end

  resources :line_items do
    post 'decrease', on: :member
    post 'increase', on: :member
  end

end

app/models/product.rb
class Product < ApplicationRecord
	before_destroy :not_referenced_by_any_line_item
  belongs_to :category

  has_attached_file :image, styles: { medium: "250x150>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  has_many :line_items

  private

   def not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, 'Line items present')
      throw :abort
    end
   end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
	before_action :set_product, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
  	@products = Product.all
  end

  def show
  end

  def new
  	@product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:category_id, :name, :description, :image, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<div class="container pt-5">
  <h2>Edit Product</h2>

  <%= form_with(model: @product, local: true) do |form| %>
    <form>
      <div class="form-group row">
        <%= form.label :name, "Name", :class =>"col-sm-2 col-form-label" %>
        <div class="col-sm-6">
          <%= form.text_field :name, :class =>"form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <%= form.label :description, "Description", :class =>"col-sm-2 col-form-label" %>
        <div class="col-sm-6">
          <%= form.text_area :description, :class =>"form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <%= form.label :price, "Price", :class =>"col-sm-2 col-form-label" %>
        <div class="col-sm-6">
          <%= form.number_field :price, :class =>"form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <%= form.label :category_id, "Choose Category", :class =>"col-sm-2 col-form-label" %>
        <div class="col-sm-6">
          <%= form.select(:category_id, Category.all.collect {|c| [ c.name, c.id ] }) %>
        </div>
      </div>

      <div class="form-group row">
        <%= form.label :image, "Choose Image", :class =>"col-sm-2 col-form-label" %>
        <div class="col-sm-6">
          <%= form.file_field :image %>
        </div>
      </div>

      <div class="actions">
        <%= form.submit %>
      </div>
    </form>
  <% end %>

  <%= link_to 'Show', @product %> |
  <%= link_to 'Back', products_path %>
</div>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container pt-4">
  <h2>Products</h2>

  <table class="table text-center">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
        <th>Category</th>
        <th>Image</th>
      </tr>
    </thead>

    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.description %></td>
          <td><%= product.price %></td>
          <td><%= product.category.name %></td>
          <td><%= image_tag product.image.url(:thumb) %></td>
          <td><%= link_to 'Show', product %></td>
          <td><%= link_to 'Edit', edit_product_path(product) %></td>
          <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to 'New Product', new_product_path %></br>

<%= link_to 'Back', authenticated_root_path %>

app/views/products/new.html.erb
<div class="container pt-5">
  <h2>New Product</h2>

  <%= form_with(model: @product, local: true) do |form| %>
    <form>
      <div class="form-group row">
        <%= form.label :name, "Name", :class =>"col-sm-2 col-form-label" %>
        <div class="col-sm-6">
          <%= form.text_field :name, :class =>"form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <%= form.label :description, "Description", :class =>"col-sm-2 col-form-label" %>
        <div class="col-sm-6">
          <%= form.text_area :description, :class =>"form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <%= form.label :price, "Price", :class =>"col-sm-2 col-form-label" %>
        <div class="col-sm-6">
          <%= form.number_field :price, :class =>"form-control" %>
        </div>
      </div>

      <div class="form-group row">
      	<%= form.label :category_id, "Choose Category", :class =>"col-sm-2 col-form-label" %>
        <div class="col-sm-6">
      	  <%= form.select(:category_id, Category.all.collect {|c| [ c.name, c.id ] }) %>
        </div>
    	</div>

      <div class="form-group row">
        <%= form.label :image, "Choose Image", :class =>"col-sm-2 col-form-label" %>
        <div class="col-sm-6">
          <%= form.file_field :image %>
        </div>
      </div>

      <div class="actions">
        <%= form.submit %>
      </div>
    </form>
  <% end %>


  <%= link_to 'Back', products_path %>
</div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container pt-5">
  
  <div>
    <strong>Name:</strong>
    <%= @product.name %>
  </div>
  <div>
    <strong>Description:</strong>
    <%= @product.description %>
  </div>
  <div>
    <strong>Price:</strong>
    <%= @product.price %>
  </div>
  <div>
    <strong>Category:</strong>
    <%= @product.category.name %>
  </div>
  <div>
    <strong>Image:</strong>
    <%= image_tag @product.image.url(:thumb) %>
  </div>
  <%= link_to 'Edit', edit_product_path(@product) %> |
  <%= link_to 'Back', products_path %>
</div>

 